# Host: 10.2.8.114  (Version: 5.7.31-log)
# Date: 2020-11-02 12:08:10
# Generator: MySQL-Front 5.3  (Build 4.234)

/*!40101 SET NAMES utf8 */;

#
# Structure for table "base_member"
#

DROP TABLE IF EXISTS `base_member`;
CREATE TABLE `base_member` (
  `member_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '会员id',
  `login_name` varchar(50) NOT NULL COMMENT '登录账号',
  `login_password` varchar(150) NOT NULL COMMENT '登录密码',
  `nick_name` varchar(100) NOT NULL COMMENT '昵称',
  `sex` tinyint(1) NOT NULL DEFAULT '0' COMMENT '性别1 男 2 女',
  `head_image` varchar(255) NOT NULL COMMENT '头像',
  `small_head_image` varchar(255) NOT NULL COMMENT '小头像',
  `big_head_image` varchar(255) NOT NULL COMMENT '大头像',
  `phone` char(11) NOT NULL COMMENT '手机号',
  `account` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '自营钱包',
  `member_type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '会员类型 1 普通 2 超级店长',
  `share_number` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '推广码数量',
  `share_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '分享红包',
  `freeze_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '冻结红包',
  `is_anchor` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为主播 1 是',
  `is_life_manager` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为生活圈店长1 是',
  `is_yp_manager` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为优品汇店长 1 是',
  `parent_id` int(11) NOT NULL DEFAULT '0' COMMENT '推广人 id ',
  `c_time` int(10) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `last_login_time` int(10) NOT NULL DEFAULT '0' COMMENT '最后登录时间',
  `login_ip` char(15) NOT NULL COMMENT '登录ip',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 正常 2 禁用 3 删除',
  `login_num` int(10) NOT NULL DEFAULT '0' COMMENT '累计登录次数',
  `fans_num` int(10) NOT NULL DEFAULT '0' COMMENT '主播粉丝数量',
  `play_num` int(10) NOT NULL DEFAULT '0' COMMENT '主播 开播次数',
  `pk_num` int(10) NOT NULL DEFAULT '0' COMMENT '主播pk次数',
  `can_play` tinyint(1) NOT NULL DEFAULT '0' COMMENT '当前主播开播权限是否已被禁用 1 已禁用',
  `rand_key` varchar(200) NOT NULL,
  `pay_password` varchar(50) NOT NULL DEFAULT '0' COMMENT '用户支付密码',
  `birthday` varchar(50) NOT NULL COMMENT '会员生日',
  `msg_json` varchar(200) NOT NULL DEFAULT '0' COMMENT '消息json 全局 1 不接受 2 接受',
  `is_authentication` tinyint(2) NOT NULL COMMENT '实名认证 0否 1是',
  `province_id` int(11) NOT NULL COMMENT '省份ID',
  `city_id` int(11) NOT NULL COMMENT '城市ID',
  `area_id` int(11) NOT NULL COMMENT '区域ID',
  `area` varchar(255) NOT NULL COMMENT '具体地址',
  `group_id` char(100) NOT NULL COMMENT '群组id',
  `open_live_num` int(11) NOT NULL COMMENT '已开播数量',
  `close_time` int(10) NOT NULL DEFAULT '0' COMMENT '用户被禁用 或者被删除的时间',
  `jpush_id` varchar(200) NOT NULL,
  `user_flags` int(11) NOT NULL DEFAULT '0' COMMENT '用户类别 0 新用户 1老用户',
  `user_salt` varchar(255) NOT NULL COMMENT '用户盐值',
  `customer_id` int(11) NOT NULL DEFAULT '0' COMMENT '老会员id',
  `is_sync` tinyint(2) NOT NULL COMMENT '是否同步优惠券 1 ：是 0：否',
  `relation_type` tinyint(2) NOT NULL DEFAULT '2' COMMENT '用户关联关系 2默认随机人 1 非默认',
  `import_integral` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '导入积分',
  `is_vip` int(11) NOT NULL COMMENT '是否是VIP',
  `counter_or_community` tinyint(4) NOT NULL COMMENT '会员是否为专柜或社区等级 1 是 0 否',
  `vip_start_time` int(15) NOT NULL COMMENT 'Vip 开始时间',
  `vip_end_time` int(15) NOT NULL COMMENT 'Vip 结束时间',
  `member_cash_coupon` decimal(11,2) NOT NULL COMMENT '会员现金券金额',
  `member_use_cash_coupon` decimal(11,2) NOT NULL COMMENT '会员已使用的现金券',
  `refer` varchar(50) NOT NULL COMMENT '邀请人账号',
  `consume_level` int(11) NOT NULL DEFAULT '0' COMMENT '会员等级',
  `wx_num` varchar(255) NOT NULL COMMENT '微信号',
  `wx_id` varchar(255) NOT NULL COMMENT '微信ID',
  `real_name` varchar(50) NOT NULL COMMENT '真实姓名（微信）',
  `level_time` int(11) NOT NULL DEFAULT '0' COMMENT '升级时间',
  `level` tinyint(1) NOT NULL DEFAULT '1' COMMENT '用户级别 1.普通用户  大于1 小助手',
  `manage_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '管理员类别 1超管 2房管',
  `manage_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '管理员状态：1启用 2禁用',
  `last_pay_time` int(10) NOT NULL DEFAULT '0' COMMENT '最后支付时间',
  `count_pay_num` int(10) NOT NULL DEFAULT '0' COMMENT '消费次数',
  `sum_order_pay` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '订单消费金额',
  `order_price_average` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '订单均价',
  `count_order_num` int(10) NOT NULL DEFAULT '0' COMMENT '订单数量（用户）',
  `change_anchor_time` int(10) NOT NULL DEFAULT '0' COMMENT '主播身份状态变更时间',
  `sum_play_time` int(10) NOT NULL DEFAULT '0' COMMENT '直播累计时长',
  `anchor_order_num` int(10) NOT NULL DEFAULT '0' COMMENT '订单数（主播直播）',
  `anchor_total_sales` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '销售额（主播直播）',
  `anchor_commission` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '直播佣金（主播直播）',
  `anchor_playback_order` int(10) NOT NULL DEFAULT '0' COMMENT '订单数（主播回放）',
  `anchor_playback_sales` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '销售额（主播回放）',
  `last_play_time` int(10) NOT NULL DEFAULT '0' COMMENT '最后直播时间',
  `recommend_sort` int(10) NOT NULL DEFAULT '0' COMMENT '推荐排序',
  `is_all_column` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为全频道 1 是',
  `is_all_goods` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为全商品 1 是',
  `mutual_fav_num` int(10) NOT NULL DEFAULT '0' COMMENT '关注数量',
  `mutual_fans_num` int(10) NOT NULL DEFAULT '0' COMMENT '粉丝数量',
  `lng` varchar(20) NOT NULL DEFAULT '' COMMENT '经度',
  `lat` varchar(20) NOT NULL DEFAULT '' COMMENT '纬度',
  `ali_id` varchar(200) NOT NULL DEFAULT '' COMMENT '支付宝ID',
  `ali_num` varchar(200) NOT NULL DEFAULT '' COMMENT '支付宝账号',
  `ali_real_name` varchar(50) NOT NULL DEFAULT '' COMMENT '支付宝真实姓名',
  `ali_openid` varchar(200) NOT NULL DEFAULT '' COMMENT '支付宝openid',
  `red_packet_balance` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '红包余额',
  `diamond_balance` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '钻石余额 (变为阳光余额)',
  `shell_balance` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '贝壳余额',
  `encode_nick` varchar(500) NOT NULL DEFAULT '' COMMENT '昵称(16进制)',
  `is_fk` tinyint(3) NOT NULL DEFAULT '0' COMMENT '虚拟用户：0.正常 1.虚拟',
  `reg_location_address_id` int(10) NOT NULL DEFAULT '0' COMMENT '注册归属地地址ID字段',
  `live_hot_sort` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '热门直播推荐排序',
  `live_hot_status` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '热门直播推荐状态：1.启用 2.禁用',
  `tag_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '热门标签ID',
  `tag_status` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '热门标签状态：1.启用 2.禁用',
  `goddess_equity` tinyint(3) NOT NULL DEFAULT '0' COMMENT '女神权益：0未开启 1已开启',
  `goddess_card_balance` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '女神卡余额',
  `experience_card_balance` int(10) NOT NULL DEFAULT '0' COMMENT '体验卡数量',
  `public_benefit_number` varchar(30) NOT NULL DEFAULT '' COMMENT '公益编号',
  `auth_role_1` tinyint(1) NOT NULL DEFAULT '1' COMMENT '区代 1否2是',
  `auth_role_2` tinyint(1) NOT NULL DEFAULT '1' COMMENT '社区长 1否2是',
  PRIMARY KEY (`member_id`),
  KEY `rand_key` (`rand_key`(191)),
  KEY `status` (`status`),
  KEY `login_name` (`login_name`),
  KEY `login_password` (`login_password`),
  KEY `nick_name` (`nick_name`),
  KEY `sex` (`sex`),
  KEY `head_image` (`head_image`(191)),
  KEY `phone` (`phone`),
  KEY `is_anchor` (`is_anchor`),
  KEY `is_life_manager` (`is_life_manager`),
  KEY `is_yp_manager` (`is_yp_manager`),
  KEY `is_fk` (`is_fk`),
  KEY `ali_id` (`ali_id`(191)),
  KEY `goddess_equity` (`goddess_equity`)
) ENGINE=InnoDB AUTO_INCREMENT=360076 DEFAULT CHARSET=utf8mb4 COMMENT='会员';
